version: 2.1

orbs:
  architect: giantswarm/architect@dev:move-lint-to-test-jobs # Test lint

workflows:
  workflow:
    jobs:
      - architect/go-test-legacy:
          name: test
      - architect/go-architect-legacy:
          name: build
          command: build
          requires:
            - test
      - architect/go-architect-legacy:
          name: deploy
          command: deploy
          requires:
            - build
          filters:
            branches:
              only: master
